name: "Run Project Status Checker"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: "main"

permissions:
  contents: write

jobs:
  run-project-status-checker:
    name: Run Project Status Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Project Status Checker
        uses: JackPlowman/project-status-checker@v1.0.0
        with:
          config_file_path:
